<a href="https://colab.research.google.com/github/sreesreevallichowdary-png/AI_ML_code_basics/blob/main/Mini_project_Task1_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import json
import pandas as pd
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Step 1: Load JSON file
with open("trends_20260411.json", "r", encoding="utf-8") as f:
    stories = json.load(f)

    # Step 2: Convert to DataFrame
df = pd.DataFrame(stories)
print(df.info)

<bound method DataFrame.info of       post_id                                              title  \
0    47737563  AI Will Be Met with Violence, and Nothing Good...
1    47736555  I run multiple $10K MRR companies on a $20/mon...
2    47733217  How We Broke Top AI Agent Benchmarks: And What...
3    47673171                            How Complex is my Code?
4    47735581  How a dancer with ALS used brainwaves to perfo...
..        ...                                                ...
108  47702196  Show HN: CSS Studio. Design by hand, code by a...
109  47715339  Show HN: Keeper – embedded secret store for Go...
110  47732148               What a legal tech demo does not show
111  47676561  Teardown of unreleased LG Rollable shows why r...
112  47734717                   A Brief History of Lab Notebooks

          category  score  num_comments           author         collected_at
0       technology     41            32       gHeadphone  2026-04-12 10:01:02
1       technology    193           123        tradertef  2026-04-12 10:01:03
2       technology    379            96           Anon84  2026-04-12 10:01:03
3       technology    126            29           speckx  2026-04-12 10:01:03
4       technology     46             8       1659447091  2026-04-12 10:01:03
..             ...    ...           ...              ...                  ...
108  entertainment    166           106         SirHound  2026-04-12 10:03:00
109  entertainment     62            32         babawere  2026-04-12 10:03:00
110  entertainment      5             0        basket278  2026-04-12 10:03:01
111  entertainment    121            56  DamnInteresting  2026-04-12 10:03:02
112  entertainment     10             0       paulpauper  2026-04-12 10:03:02

[113 rows x 7 columns]>

In [3]:
df.shape

(113, 7)

In [4]:
df.head(10)

,post_id,title,category,score,num_comments,author,collected_at
0,47737563,"AI Will Be Met with Violence, and Nothing Good...",technology,41,32,gHeadphone,2026-04-12 10:01:02
1,47736555,I run multiple $10K MRR companies on a $20/mon...,technology,193,123,tradertef,2026-04-12 10:01:03
2,47733217,How We Broke Top AI Agent Benchmarks: And What...,technology,379,96,Anon84,2026-04-12 10:01:03
3,47673171,How Complex is my Code?,technology,126,29,speckx,2026-04-12 10:01:03
4,47735581,How a dancer with ALS used brainwaves to perfo...,technology,46,8,1659447091,2026-04-12 10:01:03
5,47731506,Advanced Mac Substitute is an API-level reimpl...,technology,243,61,zdw,2026-04-12 10:01:03
6,47730194,Cirrus Labs to join OpenAI,technology,267,127,seekdeep,2026-04-12 10:01:03
7,47727960,Show HN: Pardonned.com – A searchable database...,technology,434,240,vidluther,2026-04-12 10:01:04
8,47735405,Software Preservation Group: C++ History Colle...,technology,23,2,quuxplusone,2026-04-12 10:01:04
9,47732402,The APL programming language source code (2012),technology,69,24,tosh,2026-04-12 10:01:04

In [5]:
df.tail(10)

,post_id,title,category,score,num_comments,author,collected_at
103,47678844,Show HN: Marimo pair – Reactive Python noteboo...,entertainment,137,33,manzt,2026-04-12 10:02:59
104,47736444,U.S. Intelligence Shows China Taking a More Ac...,entertainment,10,0,Teever,2026-04-12 10:02:59
105,47705413,Show HN: I built a Cargo-like build tool for C...,entertainment,169,166,randerson_112,2026-04-12 10:02:59
106,47704430,Can It Resolve Doom? Game Engine in 2k DNS Rec...,entertainment,9,2,choult,2026-04-12 10:02:59
107,47702647,"Launch HN: Relvy (YC F24) – On-call runbooks, ...",entertainment,48,25,behat,2026-04-12 10:03:00
108,47702196,"Show HN: CSS Studio. Design by hand, code by a...",entertainment,166,106,SirHound,2026-04-12 10:03:00
109,47715339,Show HN: Keeper – embedded secret store for Go...,entertainment,62,32,babawere,2026-04-12 10:03:00
110,47732148,What a legal tech demo does not show,entertainment,5,0,basket278,2026-04-12 10:03:01
111,47676561,Teardown of unreleased LG Rollable shows why r...,entertainment,121,56,DamnInteresting,2026-04-12 10:03:02
112,47734717,A Brief History of Lab Notebooks,entertainment,10,0,paulpauper,2026-04-12 10:03:02

In [6]:
# Inspect & Handle Missing Values_All columns data types
#Display the data types of all columns.
print("Column Names:")
print(df.columns.tolist())
print("\nData Types:")
print(df.dtypes)

Column Names:
['post_id', 'title', 'category', 'score', 'num_comments', 'author', 'collected_at']

Data Types:
post_id          int64
title           object
category        object
score            int64
num_comments     int64
author          object
collected_at    object
dtype: object

In [7]:
#Cleaing#Inspect & Handle Missing Values
#Count the number of missing values in each column.
print("Missing Values:")
print(df.isnull().sum())
print(f"\nTotal missing values: {df.isnull().sum().sum()}")

Missing Values:
post_id         0
title           0
category        0
score           0
num_comments    0
author          0
collected_at    0
dtype: int64

Total missing values: 0

In [8]:
#Cleaing
#Duplicate Rows
# Check for duplicates
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

if duplicates > 0:
    print("\nDuplicate rows:")
    print(df[df.duplicated(keep=False)])

Number of duplicate rows: 0

In [9]:
# Check if categorical columns are properly typed
print("Unique values in categorical columns:\n")

categorical_cols = ['category', 'author','num_comments','collected_at']
for col in categorical_cols:
    print(f"{col}: {df[col].unique()}")
    print(f"  Count: {df[col].nunique()} categories\n")

Unique values in categorical columns:

category: ['technology' 'worldnews' 'sports' 'science' 'entertainment']
  Count: 5 categories

author: ['gHeadphone' 'tradertef' 'Anon84' 'speckx' '1659447091' 'zdw' 'seekdeep'
 'vidluther' 'quuxplusone' 'tosh' 'saikatsg' 'duguyue100' 'nickgreg'
 'pabs3' 'lermontov' 'hmokiguess' 'rooppal' 'maxloh' 'danoandco'
 'roxolotl' 'ellieh' 'c420' 'Teever' 'classichasclass' 'facundo_olano'
 'neversaydie' 'jkl5xx' 'sandebert' 'Ryan5453' 'NaOH' 'thywis' 'WerWolv'
 'etherio' 'fanf2' 'zixuanlimit' 'tlhunter' 'chabons' 'bpierre' 'breve'
 'quaintdev' 'nsoonhui' 'rryan' 'voisin' 'ductionist' 'Bender' 'maltalex'
 'iceberger2001' 'GenericCanadian' 'joko42' 'choult' 'JKCalhoun'
 'AlexeyBrin' 'joeax' 'russellharper' 'surgical_fire' 'pruz'
 'JumpCrisscross' 'tantalor' 'sprado' 'keepamovin' 'akyuu' 'testing22321'
 'steadcast' 'pella' 'bookofjoe' 'fi-le' 'alsetmusic' 'sohkamyung'
 'PaulHoule' 'hopechong' 'zdgeier' 'giuliomagnifico' 'elsewhen'
 'LabsLucas' 'teleforce' 'salt4034' 'defrost' 'normanvalentine'
 'anigbrowl' 'novalis78' 'maouida' 'olleeolleeollee' 'iamflimflam1'
 'chrisecker' 'zachdive' 'thm' 'tclancy' 'manzt' 'randerson_112' 'behat'
 'SirHound' 'babawere' 'basket278' 'DamnInteresting' 'paulpauper']
  Count: 95 categories

num_comments: [ 32 123  96  29   8  61 127 240   2  24 109  34 250  21 382   0  41  83
 733  51 683  78  98 266 134 124 832  12   7  48  15  66 262  69 367  38
 334  19  18  26   4 160 146  52  25  49 273   5  36   3 264 192 163  31
   1 231 317  54 184  23  64 628  13   6  33  11  37 166 106  56]
  Count: 70 categories

collected_at: ['2026-04-12 10:01:02' '2026-04-12 10:01:03' '2026-04-12 10:01:04'
 '2026-04-12 10:01:05' '2026-04-12 10:01:06' '2026-04-12 10:01:07'
 '2026-04-12 10:01:08' '2026-04-12 10:01:09' '2026-04-12 10:01:10'
 '2026-04-12 10:01:13' '2026-04-12 10:01:15' '2026-04-12 10:01:18'
 '2026-04-12 10:01:20' '2026-04-12 10:01:22' '2026-04-12 10:01:23'
 '2026-04-12 10:01:25' '2026-04-12 10:01:27' '2026-04-12 10:01:28'
 '2026-04-12 10:01:29' '2026-04-12 10:01:30' '2026-04-12 10:01:32'
 '2026-04-12 10:01:33' '2026-04-12 10:01:34' '2026-04-12 10:01:37'
 '2026-04-12 10:01:38' '2026-04-12 10:01:43' '2026-04-12 10:01:44'
 '2026-04-12 10:01:45' '2026-04-12 10:01:50' '2026-04-12 10:01:53'
 '2026-04-12 10:01:54' '2026-04-12 10:01:55' '2026-04-12 10:01:56'
 '2026-04-12 10:01:58' '2026-04-12 10:01:59' '2026-04-12 10:02:01'
 '2026-04-12 10:02:04' '2026-04-12 10:02:05' '2026-04-12 10:02:07'
 '2026-04-12 10:02:11' '2026-04-12 10:02:12' '2026-04-12 10:02:18'
 '2026-04-12 10:02:19' '2026-04-12 10:02:22' '2026-04-12 10:02:23'
 '2026-04-12 10:02:28' '2026-04-12 10:02:29' '2026-04-12 10:02:30'
 '2026-04-12 10:02:35' '2026-04-12 10:02:38' '2026-04-12 10:02:41'
 '2026-04-12 10:02:42' '2026-04-12 10:02:46' '2026-04-12 10:02:47'
 '2026-04-12 10:02:51' '2026-04-12 10:02:52' '2026-04-12 10:02:53'
 '2026-04-12 10:02:55' '2026-04-12 10:02:56' '2026-04-12 10:02:57'
 '2026-04-12 10:02:58' '2026-04-12 10:02:59' '2026-04-12 10:03:00'
 '2026-04-12 10:03:01' '2026-04-12 10:03:02']
  Count: 65 categories

In [10]:
df.describe()

            post_id        score  num_comments
count  1.130000e+02   113.000000     113.00000
mean   4.771060e+07   180.380531      95.20354
std    2.463887e+04   241.031612     152.07512
min    4.765050e+07     1.000000       0.00000
25%    4.769811e+07    29.000000       7.00000
50%    4.772092e+07   102.000000      34.00000
75%    4.773041e+07   243.000000     123.00000
max    4.773756e+07  1533.000000     832.00000

In [11]:
#save cleaned data to csv
df.to_csv("trends_20260411.csv",index=False)
print("cleaning complete.Saved to trends_20260411.csv")

cleaning complete.Saved to trends_20260411.csv